@php
    $text = collect([
        'DECLENCHEMENT SYSTEMATIQUE DEPART : TP2_PYRO 22 [V_TP1000] - ALARME AUTOMATIQUE (BOGIS-BOSSEY - INSTITUT OECUMENIQUE (ALR);BATIMENT PRINCIPAL;CHEMIN CHENEVIERE 2)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : TP2_PYRO 22 [V_TP1000] - ALARME AUTOMATIQUE (CHAVANNES-DE-BOGIS - MANOR CENTRE COMMERCIAL (ALR);MALL ET BOUTIQUE;CHEMIN INDUSTRIEL 1)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : TP2_PYRO 22 [V_TP1000] - TECHNIQUE FUMEE SUSPECTE (CHAVANNES-DES-BOIS - TRONCON - ROUTE DE LA BRANVAUDE)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : VCI_PYRO 01 - OFFICIER DE SERVICE (COMMUGNY - ROUTE DE COPPET 8)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : TP2_PYRO 22 [V_TP1000] - TECHNIQUE ODEUR DE GAZ (COPPET - CHEMIN DES PESSULES 21A)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : VTU_PYRO 72 [MIS_HYD] - HYDROCARBURE ROUTE (FOUNEX - CARREFOUR CHAMPS BLANCS)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : PONT_PYRO 73 [MIS_INOND] - TECHNIQUE INONDATION DE CHAUFFERIE (MIES - CHEMIN DE LA FAVERGE 10A)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : TP2_PYRO 22, M_ACCOMP 01, VM_PYRO 61 [V_MOD-ACC] - FEU DE CHAUFFERIE (TANNAY - ROUTE DE MALCROISSANT 11)',
        'DECLENCHEMENT SYSTEMATIQUE DEPART : EA_PYRO 11 - TENTATIVE DE SUICIDE (EYSINS - ROUTE DU PETIT-EYSINS 10)',
    ])->random();
@endphp

{{ $text }}